name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  init-openwrt:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true # Initialize and update submodules

      # Ensure necessary directories exist and set permissions
      - name: Prepare OpenWrt directories
        run: |
          mkdir -p openwrt
          chmod -R 777 openwrt

      # Copy feeds.conf.default to the openwrt directory
      - name: Copy feeds.conf.default
        run: cp feeds.conf.default openwrt/feeds.conf.default

      # Create symbolic links for configuration files
      - name: Create symbolic links
        run: |
          ln -sf ../conf/full_raspberrypi_bcm27xx_bcm2709/.config openwrt/.config
          ln -sf ../conf/full_raspberrypi_bcm27xx_bcm2709/files openwrt/files
          ln -sf ../conf/full_raspberrypi_bcm27xx_bcm2709/patches openwrt/patches

      # Update and install OpenWrt feeds
      - name: Update and install OpenWrt feeds
        run: |
          docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds update -a
          docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds install -a

      # Initialize quilt
      - name: Initialize quilt
        run: docker compose run --rm chirpstack-gateway-os quilt init

      # Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python3

      # Build OpenWrt
      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j1 V=s


