name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
env:
  ENV: full_raspberrypi_bcm27xx_bcm2709

jobs:
  init-openwrt:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true # Initialize and update submodules

      # Ensure necessary directories exist and set permissions
      - name: Prepare OpenWrt directories
        run: |
          mkdir -p openwrt
          chmod -R 777 .
          

      - name: Update and install OpenWrt feeds
        run: |
          docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds update -a
          docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds install -a

      # Initialize quilt
      - name: Initialize quilt
        run: docker compose run --rm chirpstack-gateway-os quilt init
      # Patch remove quilt
      # - name: Run quilt
      #   run: docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt && quilt pop -a"

      # Copy feeds.conf.default to the openwrt directory
      - name: Swtiching config to full_raspberrypi_bcm27xx_bcm2709
        run: |
          rm -f conf/files conf/patches conf/.config
          ln -s ${ENV}/files conf/files
          ln -s ${ENV}/patches conf/patches
          ln -s ${ENV}/.config conf/.config
      - name: Apply patches using quilt
        run: |
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt && quilt push -a"
    
      # # Copy feeds.conf.default to the openwrt directory
      # - name: Copy feeds.conf.default
      #   run: cp feeds.conf.default openwrt/feeds.conf.default
      - name: Build OpenWrt
        run: |
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt && make defconfig -j$(nproc)"
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt &&  make download -j$(nproc) V=s"
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt &&  make -j$(nproc)"

      # List contents of targets folder and all subfolders
      - name: List OpenWrt build output (targets)
        run: |
          ls -lR openwrt/bin/targets
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: full_raspberrypi_bcm27xx_bcm2709
          path: openwrt/bin/targets/bcm27xx/bcm2709

