name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout chirpstack-gateway-os
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Initialize submodules
        run: git submodule update --init --recursive
        
      # Set permissions for openwrt directory
      - name: Set permissions for the openwrt directory
        run: sudo chown -R $USER:$USER openwrt
      # - name: Install build dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
      #       gettext libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file

      - name: Init build system
        run: make init


