name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout chirpstack-gateway-os
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Initialize submodules
        run: git submodule update --init --recursive
        
      # Set permissions for openwrt directory
      - name: Set permissions for the openwrt directory
        run: sudo chown -R $USER:$USER openwrt

      # Ensure Git treats the workspace as a safe directory
      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Debug directory structure and permissions
        run: |
          ls -l openwrt
          whoami
          pwd
          ls -ld $GITHUB_WORKSPACE
              
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext libncurses-dev libssl-dev rsync unzip zlib1g-dev file

      - name: Init build system
        run: make init


