name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
env:
  ENV: base_raspberrypi_bcm27xx_bcm2709

jobs:
  init-openwrt:
    runs-on: ubuntu-latest
    timeout-minutes: 720

    steps:
      - run: df -h
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          sudo apt-get purge -y openjdk-\* || true
          sudo apt-get purge -y default-jre default-jdk temurin-\* || true
          sudo apt-get purge -y mono-complete mono-devel mono-runtime mono-runtime-common mono-runtime-sgen mono-runtime-mono || true
          sudo apt-get purge -y postgresql\* || true
          sudo apt-get purge -y firefox\* || true
          sudo apt-get autoremove -y
          sudo rm -rf /usr/lib/jvm/temurin*
      - run: df -h

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true # Initialize and update submodules

      # Ensure necessary directories exist and set permissions
      - name: Prepare OpenWrt directories
        run: |
          mkdir -p openwrt
          chmod -R 777 .
          

      - name: Make init
        run: |
          make init

      # - name: Update and install OpenWrt feeds
      #   run: |
      #     docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds update -a
      #     docker compose run --rm chirpstack-gateway-os openwrt/scripts/feeds install -a

      # # Initialize quilt
      # - name: Initialize quilt
      #   run: docker compose run --rm chirpstack-gateway-os quilt init
      # Patch remove quilt
      # - name: Run quilt
      #   run: docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt && quilt pop -a"
      - name: List Docker images and containers
        run: |
          docker images
          docker ps -a

      # Copy feeds.conf.default to the openwrt directory
      - name: Switching config to full_raspberrypi_bcm27xx_bcm2709
        run: |
          docker compose run --rm --user $(id -u):$(id -g) chirpstack-gateway-os make switch-env ENV=${ENV}

      # - name: Swtiching config to ${ENV}
      #   run: |
      #     make devshell &&  make switch-env ENV=${ENV}

      # List contents of targets folder and all subfolders
      - name: List OpenWrt folder contents
        run: |
          ls -lR .
          echo "${ENV}"
      # - name: Apply patches using quilt
      #   run: |
      #     docker compose run --rm --user $(id -u):$(id -g) chirpstack-gateway-os bash -c "cd openwrt && quilt push -a"
    
      # # Copy feeds.conf.default to the openwrt directory
      # - name: Copy feeds.conf.default
      #   run: cp feeds.conf.default openwrt/feeds.conf.default
      - name: Build OpenWrt
        run: |
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt && make defconfig -j$(nproc)"
          docker compose run --rm chirpstack-gateway-os bash -c "cd openwrt &&  make download -j$(nproc) V=s"
          docker compose run --rm chirpstack-gateway-os bash -c "make -j$(nproc) V=s"

      # List contents of targets folder and all subfolders
      - name: List OpenWrt build output (targets)
        run: |
          ls -lR openwrt/bin/targets
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: base_raspberrypi_bcm27xx_bcm2709
          path: openwrt/bin/targets/
          # path: openwrt/bin/targets/bcm27xx/bcm2709

